In [27]:
import numpy as np
import pandas as pd

np.random.seed(0)

df = pd.read_csv("base_datos_2008.csv", nrows=1000)

In [28]:
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,4.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,5.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,3.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2008,1,3,4,926.0,930,1054.0,1100,WN,1746,...,3.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,3.0,10.0,0,NaN,0,2.0,0.0,0.0,0.0,32.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2008,1,3,4,2154.0,2040,2314.0,2205,WN,428,...,4.0,13.0,0,NaN,0,2.0,0.0,0.0,0.0,67.0
996,2008,1,3,4,1322.0,1245,1444.0,1410,WN,500,...,3.0,15.0,0,NaN,0,34.0,0.0,0.0,0.0,0.0
997,2008,1,3,4,701.0,700,823.0,825,WN,565,...,4.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
998,2008,1,3,4,1012.0,1010,1136.0,1135,WN,752,...,5.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
999,2008,1,3,4,834.0,830,955.0,955,WN,762,...,4.0,18.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [36]:
df = df.sample(frac=0.5)

In [37]:
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
103,2008,1,3,4,650.0,650,748.0,750,WN,670,...,3.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
141,2008,1,3,4,701.0,645,802.0,745,WN,337,...,7.0,12.0,0,NaN,0,16.0,0.0,1.0,0.0,0.0
698,2008,1,3,4,2245.0,2125,115.0,5,WN,2786,...,4.0,8.0,0,NaN,0,45.0,0.0,0.0,0.0,25.0
261,2008,1,3,4,1118.0,1110,1225.0,1215,WN,3423,...,3.0,14.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
971,2008,1,3,4,1229.0,1135,1341.0,1240,WN,891,...,2.0,21.0,0,NaN,0,1.0,0.0,7.0,0.0,53.0
819,2008,1,3,4,1305.0,1245,1558.0,1545,WN,792,...,7.0,12.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
578,2008,1,3,4,1914.0,1755,2122.0,2005,WN,1507,...,1.0,14.0,0,NaN,0,0.0,0.0,0.0,0.0,77.0
264,2008,1,3,4,1049.0,1040,1509.0,1510,WN,2113,...,4.0,9.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
298,2008,1,3,4,1821.0,1730,1946.0,1855,WN,641,...,6.0,12.0,0,NaN,0,9.0,0.0,0.0,0.0,42.0
654,2008,1,3,4,2014.0,2000,2143.0,2140,WN,2135,...,3.0,9.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
738,2008,1,3,4,1149.0,1115,1416.0,1400,WN,3763,...,3.0,9.0,0,NaN,0,12.0,0.0,0.0,0.0,4.0
823,2008,1,3,4,955.0,935,1242.0,1230,WN,3757,...,3.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
316,2008,1,3,4,715.0,720,926.0,935,WN,1059,...,3.0,13.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
331,2008,1,3,4,1149.0,1145,1639.0,1650,WN,205,...,3.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
501,2008,1,3,4,1920.0,1850,2140.0,2110,WN,321,...,9.0,10.0,0,NaN,0,30.0,0.0,0.0,0.0,0.0
262,2008,1,3,4,1456.0,1445,1920.0,1920,WN,120,...,4.0,14.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
175,2008,1,3,4,1030.0,1030,1545.0,1545,WN,762,...,3.0,18.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
196,2008,1,3,4,2015.0,1945,2101.0,2040,WN,725,...,4.0,8.0,0,NaN,0,3.0,0.0,0.0,0.0,18.0
736,2008,1,3,4,916.0,820,1142.0,1105,WN,319,...,4.0,12.0,0,NaN,0,13.0,0.0,0.0,0.0,24.0
587,2008,1,3,4,1544.0,1525,1744.0,1740,WN,1063,...,5.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
643,2008,1,3,4,1730.0,1620,2028.0,1920,WN,1484,...,8.0,14.0,0,NaN,0,68.0,0.0,0.0,0.0,0.0
883,2008,1,3,4,822.0,805,921.0,910,WN,2177,...,3.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
389,2008,1,3,4,1556.0,1440,1804.0,1655,WN,746,...,4.0,12.0,0,NaN,0,69.0,0.0,0.0,0.0,0.0
576,2008,1,3,4,730.0,720,940.0,925,WN,889,...,3.0,10.0,0,NaN,0,0.0,0.0,5.0,10.0,0.0
142,2008,1,3,4,1556.0,1455,1704.0,1600,WN,354,...,9.0,18.0,0,NaN,0,61.0,0.0,3.0,0.0,0.0
568,2008,1,3,4,1740.0,1715,1835.0,1815,WN,3238,...,5.0,13.0,0,NaN,0,11.0,0.0,0.0,0.0,9.0
531,2008,1,3,4,2135.0,2125,2239.0,2235,WN,727,...,4.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
481,2008,1,3,4,1905.0,1850,2010.0,2000,WN,1493,...,5.0,14.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
27,2008,1,3,4,1954.0,1925,2239.0,2235,WN,1754,...,3.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
862,2008,1,3,4,1110.0,1055,1307.0,1300,WN,2019,...,4.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
706,2008,1,3,4,1901.0,1600,2113.0,1815,WN,3587,...,6.0,12.0,0,NaN,0,22.0,0.0,0.0,0.0,156.0
31,2008,1,3,4,1008.0,1005,1234.0,1255,WN,543,...,5.0,6.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
496,2008,1,3,4,1101.0,1055,1142.0,1145,WN,454,...,6.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
784,2008,1,3,4,1947.0,1935,2110.0,2100,WN,727,...,4.0,14.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
957,2008,1,3,4,1740.0,1645,1948.0,1855,WN,714,...,7.0,6.0,0,NaN,0,8.0,0.0,0.0,0.0,45.0
693,2008,1,3,4,1338.0,1300,1617.0,1545,WN,208,...,4.0,7.0,0,NaN,0,32.0,0.0,0.0,0.0,0.0
108,2008,1,3,4,1306.0,1250,1406.0,1355,WN,1838,...,2.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
996,2008,1,3,4,1322.0,1245,1444.0,1410,WN,500,...,3.0,15.0,0,NaN,0,34.0,0.0,0.0,0.0,0.0
367,2008,1,3,4,2001.0,1930,2118.0,2045,WN,810,...,4.0,9.0,0,NaN,0,0.0,0.0,2.0,0.0,31.0
993,2008,1,3,4,1055.0,1050,1620.0,1630,WN,506,...,2.0,11.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
310,2008,1,3,4,1558.0,1530,2049.0,2040,WN,1050,...,4.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
710,2008,1,3,4,901.0,900,1101.0,1105,WN,748,...,5.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
672,2008,1,3,4,2106.0,1925,2.0,2215,WN,714,...,5.0,21.0,0,NaN,0,48.0,0.0,6.0,0.0,53.0
311,2008,1,3,4,1940.0,1855,29.0,2355,WN,1583,...,3.0,9.0,0,NaN,0,22.0,0.0,0.0,0.0,12.0
614,2008,1,3,4,1243.0,1155,1439.0,1400,WN,1308,...,2.0,18.0,0,NaN,0,0.0,0.0,0.0,0.0,39.0
77,2008,1,3,4,958.0,900,1052.0,950,WN,1574,...,4.0,14.0,0,NaN,0,0.0,0.0,4.0,0.0,58.0
635,2008,1,3,4,1524.0,1500,1714.0,1650,WN,1320,...,5.0,13.0,0,NaN,0,0.0,0.0,17.0,0.0,7.0
239,2008,1,3,4,1609.0,1540,1732.0,1700,WN,709,...,7.0,21.0,0,NaN,0,26.0,0.0,3.0,0.0,3.0
740,2008,1,3,4,2217.0,2110,47.0,2350,WN,205,...,5.0,12.0,0,NaN,0,25.0,0.0,0.0,0.0,32.0
230,2008,1,3,4,1825.0,1745,114.0,50,WN,512,...,6.0,13.0,0,NaN,0,10.0,0.0,0.0,0.0,14.0

In [39]:
df.dtypes

Year                   int64
Month                  int64
DayofMonth             int64
DayOfWeek              int64
DepTime              float64
CRSDepTime             int64
ArrTime              float64
CRSArrTime             int64
UniqueCarrier         object
FlightNum              int64
TailNum               object
ActualElapsedTime    float64
CRSElapsedTime         int64
AirTime              float64
ArrDelay             float64
DepDelay             float64
Origin                object
Dest                  object
Distance               int64
TaxiIn               float64
TaxiOut              float64
Cancelled              int64
CancellationCode      object
Diverted               int64
CarrierDelay         float64
WeatherDelay         float64
NASDelay             float64
SecurityDelay        float64
LateAircraftDelay    float64
dtype: object

In [40]:
data = df.groupby(by=["TaxiOut"])["DepDelay", "ArrDelay"].mean()
data.head()
data.describe()

<ipython-input-40-ebf29a6a71e8>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  data = df.groupby(by=["TaxiOut"])["DepDelay", "ArrDelay"].mean()

        DepDelay   ArrDelay
count  13.000000  13.000000
mean   32.662088  25.698168
std    15.890376  19.662144
min    10.200000  -0.200000
25%    26.600000  14.333333
50%    28.000000  17.000000
75%    36.333333  34.000000
max    66.714286  66.666667

In [41]:
df2 = df[np.abs(df["DepDelay"])>60]

In [42]:
df2

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
698,2008,1,3,4,2245.0,2125,115.0,5,WN,2786,...,4.0,8.0,0,NaN,0,45.0,0.0,0.0,0.0,25.0
578,2008,1,3,4,1914.0,1755,2122.0,2005,WN,1507,...,1.0,14.0,0,NaN,0,0.0,0.0,0.0,0.0,77.0
643,2008,1,3,4,1730.0,1620,2028.0,1920,WN,1484,...,8.0,14.0,0,NaN,0,68.0,0.0,0.0,0.0,0.0
389,2008,1,3,4,1556.0,1440,1804.0,1655,WN,746,...,4.0,12.0,0,NaN,0,69.0,0.0,0.0,0.0,0.0
142,2008,1,3,4,1556.0,1455,1704.0,1600,WN,354,...,9.0,18.0,0,NaN,0,61.0,0.0,3.0,0.0,0.0
706,2008,1,3,4,1901.0,1600,2113.0,1815,WN,3587,...,6.0,12.0,0,NaN,0,22.0,0.0,0.0,0.0,156.0
672,2008,1,3,4,2106.0,1925,2.0,2215,WN,714,...,5.0,21.0,0,NaN,0,48.0,0.0,6.0,0.0,53.0
740,2008,1,3,4,2217.0,2110,47.0,2350,WN,205,...,5.0,12.0,0,NaN,0,25.0,0.0,0.0,0.0,32.0

In [34]:
df3 = df[np.abs(df["DepDelay"]) == 0]

In [35]:
df3

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
55,2008,1,3,4,700.0,700,851.0,900,WN,449,...,6.0,6.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
175,2008,1,3,4,1030.0,1030,1545.0,1545,WN,762,...,3.0,18.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
103,2008,1,3,4,650.0,650,748.0,750,WN,670,...,3.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
251,2008,1,3,4,805.0,805,909.0,905,WN,711,...,3.0,16.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [ ]:
data2 = df.groupby(by=["Time", "Origin"], as_index = False)["FlightNum","DepDelay", "ArrDelay"].mean()